---
default: true

# Fix any fixable errors (depending on the markdownlint wrapper tool used)
fix: true

# The source file for a documentation of a tool starts with h2 because h1 is
# generated during the build.
first-line-h1: false

# Errors from .html to .md rename (first step in HTML to Markdown conversion)
no-blanks-blockquote: false
no-multiple-space-blockquote: false
ul-style: false
ul-indent: false
no-trailing-spaces: false
no-hard-tabs: false
no-reversed-links: false
no-multiple-blanks: false
line-length: false
no-missing-space-atx: false
no-multiple-space-atx: false
no-missing-space-closed-atx: false
no-trailing-punctuation: false
ol-prefix: false
blanks-around-lists: false
no-inline-html: false
no-bare-urls: false
no-space-in-links: false
no-empty-links: false
no-space-in-emphasis: false
no-alt-text: false
emphasis-style: false
reference-links-images: false
table-pipe-style: false
table-column-count: false
blanks-around-tables: false
# The block above this is to be eventually removed.

# The warning is triggered even for code blocks with language set to text,
# so r.fuzzy.system syntax triggers the warning even when completely valid.
commands-show-output: false
