---
default: true

# Fix any fixable errors (depending on the markdownlint wrapper tool used)
fix: true

# The source file for a documentation of a tool starts with h2 because h1 is
# generated during the build.
first-line-h1: false

# Errors from .html to .md rename (first step in HTML to Markdown conversion)
line-length: false
no-inline-html: false
# The block above this is to be eventually removed.

# The warning is triggered even for code blocks with language set to text,
# so r.fuzzy.system syntax triggers the warning even when completely valid.
commands-show-output: false
